(defun str/head (a-string) (char a-string 0))

(defun str/rest (a-string) (subseq a-string 1 (length a-string)))

(defun open-paren-p (a-char) (char= a-char #\())

(defun close-paren-p (a-char) (char= a-char #\)))

(defun instructions->floor (instructions &optional (floor 0))
  (cond ((= (length instructions) 0) floor)
        ((open-paren-p (str/head instructions))
         (instructions->floor (str/rest instructions) (+ floor 1)))
        ((close-paren-p (str/head instructions))
         (instructions->floor (str/rest instructions) (- floor 1)))
        (t (instructions->floor (str/rest instructions) floor))))

(defun instructions->basement-pos (instructions &optional (floor 0) (pos 0))
  (cond ((or (< floor 0) (= (length instructions) 0)) pos)
        ((open-paren-p (str/head instructions))
         (instructions->basement-pos (str/rest instructions) (+ floor 1) (+ pos 1)))
        ((close-paren-p (str/head instructions))
         (instructions->basement-pos (str/rest instructions) (- floor 1) (+ pos 1)))
        (t (instructions->basement-pos (str/rest instructions) floor (+ pos 1)))))

(defun not-quite-lisp ()
  (let ((instructions (uiop:read-file-string "day01.txt")))
    (format t "2015 day 1 part 1: ~a~%" (instructions->floor instructions))
    (format t "2015 day 1 part 2: ~a~%" (instructions->basement-pos instructions))))


(defun parse-dimensions (line)
  (let ((cleaned (string-right-trim "\n" line)))
    (let ((tokens (uiop:split-string cleaned :separator "x")))
      (mapcar #'parse-integer tokens))))

(defun dims->paper (dimensions)
  (let ((l (first dimensions))
        (w (second dimensions))
        (h (third dimensions)))
    (let ((a1 (* l w))
          (a2 (* w h))
          (a3 (* h l)))
      (+ (* 2 a1) (* 2 a2) (* 2 a3) (min a1 a2 a3)))))

(defun dimensions->ribbon (dimensions)
  (let ((sorted (sort dimensions #'<)))
    (let ((a (first sorted))
          (b (second sorted))
          (c (third sorted)))
      (+ (* 2 a) (* 2 b) (* a b c)))))

(defun i-was-told-there-would-be-no-math ()
  (let ((lines (uiop:read-file-lines "day02.txt")))
    (let ((puzzle-input (mapcar 'parse-dimensions lines)))
      (let ((paper-feet (mapcar 'dims->paper puzzle-input))
            (ribbon-feet (mapcar 'dimensions->ribbon puzzle-input)))
        (format t "2015 day 2 part 1: ~a~%" (reduce '+ paper-feet))
        (format t "2015 day 2 part 2: ~a~%" (reduce #'+ ribbon-feet))))))

(defun 2dgrid/update-pos (pos step)
  (let ((x (aref pos 0))
        (y (aref pos 1)))
    (cond ((char= step #\>) (vector (+ x 1) y))
          ((char= step #\<) (vector (- x 1) y))
          ((char= step #\^) (vector x (+ y 1)))
          ((char= step #\v) (vector x (- y 1)))
          (t pos))))

(defun 2dgrid/santa-pos (steps &optional (pos #(0 0)) (seen (make-hash-table :test equalp)))
  (if (= (length steps) 0)
      (length (alexandria:hash-table-keys seen))
      (let ((new-pos (2dgrid/update-pos pos (str/head steps))))
        (if (gethash new-pos seen)
            (2dgrid/santa-pos (str/rest steps) new-pos seen)
            (2dgrid/santa-pos (str/rest steps) new-pos (setf (gethash new-pos seen) t))))))
